// Code generated by goctl. DO NOT EDIT.
package types

type JwtToken struct {
	AccessToken  string `json:"accessToken,omitempty"`
	AccessExpire int64  `json:"accessExpire,omitempty"`
	RefreshAfter int64  `json:"refreshAfter,omitempty"`
}

type LoginReq struct {
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Smscode  string `json:"smscode"` //短信码
}

type RegisterReq struct {
	Username string `json:"username"`
	Mobile   string `json:"mobile"` //基本一个手机号码就完事
	Password string `json:"password"`
	Smscode  string `json:"smscode"` //短信码
}

type UserReply struct {
	Auid     int64  `json:"auid"`
	Uid      int64  `json:"uid"`
	Beid     int64  `json:"beid"`  //应用id
	Ptyid    int64  `json:"ptyid"` //对应平台
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Openid   string `json:"openid"`
	Avator   string `json:"avator"`
	Gender   string `json:"gender"`
	JwtToken
}
