// Code generated by goctl. DO NOT EDIT!
// Source: common.proto

package server

import (
	"context"

	"datacenter/common/rpc/common"
	"datacenter/common/rpc/internal/logic"
	"datacenter/common/rpc/internal/svc"
)

type CommonServer struct {
	svcCtx *svc.ServiceContext
}

func NewCommonServer(svcCtx *svc.ServiceContext) *CommonServer {
	return &CommonServer{
		svcCtx: svcCtx,
	}
}

func (s *CommonServer) GetAppConfig(ctx context.Context, in *common.AppConfigReq) (*common.AppConfigResp, error) {
	l := logic.NewGetAppConfigLogic(ctx, s.svcCtx)
	return l.GetAppConfig(in)
}

func (s *CommonServer) GetBaseApp(ctx context.Context, in *common.BaseAppReq) (*common.BaseAppResp, error) {
	l := logic.NewGetBaseAppLogic(ctx, s.svcCtx)
	return l.GetBaseApp(in)
}
