// Code generated by goctl. DO NOT EDIT!
// Source: search.proto

package server

import (
	"context"

	"datacenter/search/rpc/internal/logic"
	"datacenter/search/rpc/internal/svc"
	"datacenter/search/rpc/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServer) ArticleInit(ctx context.Context, in *search.Request) (*search.Response, error) {
	l := logic.NewArticleInitLogic(ctx, s.svcCtx)
	return l.ArticleInit(in)
}

func (s *SearchServer) ArticleStore(ctx context.Context, in *search.ArticleReq) (*search.Response, error) {
	l := logic.NewArticleStoreLogic(ctx, s.svcCtx)
	return l.ArticleStore(in)
}

func (s *SearchServer) ArticleSearch(ctx context.Context, in *search.SearchReq) (*search.ArticleResp, error) {
	l := logic.NewArticleSearchLogic(ctx, s.svcCtx)
	return l.ArticleSearch(in)
}
